Offene Infrastruktur
hbz/slides pull request #68
Opened 2021-02-09 13:25 UTC by acka47

Schaut euch das am besten alle mal an.

2021-02-09 13:53 UTC, dr0i requested changes

2021-02-09 13:53 UTC, dr0i commented on 2021-01-offene-infrastruktur/index.html
> +				<p><span class="fragment">Blogbeiträge, Zeitschriftenartikel<br/>(siehe <a href="#/49">weiterführende Informationen</a>)</span></p>
Das linkt nicht zu Blogbeiträgen usw.

2021-02-09 13:54 UTC, dr0i commented on 2021-01-offene-infrastruktur/index.html
> +				<p><span class="fragment">Blogbeiträge, Zeitschriftenartikel<br/>(siehe <a href="#/49">weiterführende Informationen</a>)</span></p>
ansonsten +1

2021-02-09 14:46 UTC, acka47 commented on 2021-01-offene-infrastruktur/index.html
> +				<p><span class="fragment">Blogbeiträge, Zeitschriftenartikel<br/>(siehe <a href="#/49">weiterführende Informationen</a>)</span></p>
Done, see 
f44c338

2021-02-09 15:10 UTC, dr0i approved these changes
+1

2021-02-10 08:34 UTC, fsteeg approved these changes
Paar Kleinigkeiten angepasst (https://github.com/hbz/slides/pull/68/commits/533edefb36e0c5712efa527a816ee6a0cf5cb8ab).

Was mir auf der Titelseite noch auffiel: Ist das für eine Beiratssitzung heute? Ich dachte das wäre eine andere Runde. Und das "Was soll das?" klingt was negativ finde ich.

2021-02-10 09:14 UTC, acka47 commented
Danke für die Kommentare, @fsteeg. Ich dachte mir schon, das jemand den Titel nicht so gut findet. Ich habe ihn nun angepasst ("Produkte, Projekte, Ziele") und in dem Zug ein paar ambitionierte aber m.E. realistische Ziele für Metafacture, SkoHub, OERSI, KIM ergänzt.

2021-02-10 12:29 UTC, TobiasNx reviewed
S. 37 
Vielleicht sollte der Twitterkommentar auf Folie 37 raus, da sich das scheinabr eher auf openrefine bezieht. Oderr ein Satz dazu, der den Kontext klärt.

S. 50 ist länger als die Seite.

Allgemein:
Öfters werden Punkte mut einer Überschrift/Schlagwort eingeleitet

"Ziele: OERSI ist meistgenutzter Dienst zur Recherche nach Hochschul-OER im deutschsprachigen Raum"
Vielleicht könnte man dann die Worte vor dem Doppelpunkt irgendwie hervorheben. Ansonsteen geht das optisch unter.

2021-02-10 12:46 UTC, katauber commented
Folie 47: Link auf Hochschulfächersystematik hat ein ")" zu viel, daher erhält man eine 404

Folie 48: "Anstatzes" -> "Ansatzes"

Folie 53: "Versuch eines Überblicks" -> ich fände es besser, einfach "Überblick" zu schreiben. Es gibt ja einen Überblick über Projekte, Zusammenhänge etc., auch wenn es noch nicht in einem endgültigen Zustand ist

Folie 57: Link zu OER-Metadatengruppe: Seite nicht gefunden. Ich glaube es müsste im Link "..Metadatengruppe" und nicht "...Metadaten-Gruppe" heißen

Ansonsten: 👍

2021-02-10 12:48 UTC, katauber reviewed
Folie 47: Link auf Hochschulfächersystematik hat ein ")" zu viel, daher erhält man eine 404

Folie 48: "Anstatzes" -> "Ansatzes"

Folie 53: "Versuch eines Überblicks" -> ich fände es besser, einfach "Überblick" zu schreiben. Es gibt ja einen Überblick über Projekte, Zusammenhänge etc., auch wenn es noch nicht in einem endgültigen Zustand ist

Folie 57: Link zu OER-Metadatengruppe: Seite nicht gefunden. Ich glaube es müsste im Link "..Metadatengruppe" und nicht "...Metadaten-Gruppe" heißen

Ansonsten: 👍

2021-02-10 13:09 UTC, acka47 commented
Danke allen! Ich habe die Kommentare mit 7544ba7  berücksichtigt und merge dann.

2021-02-10 13:09 UTC, merged